# Generated by Django 5.1.6 on 2025-03-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(default='https://media.istockphoto.com/id/1033799364/vector/workflow-process-icon-in-flat-style-gear-cog-wheel-with-arrows-vector-illustration-on-white.jpg?s=612x612&w=0&k=20&c=w0GBtP-wdqzKXr-H2tEpXZleFuCVhNIeg-d4sypTTZ0=', max_length=500),
            preserve_default=False,
        ),
    ]
